package frc.robot;

import static edu.wpi.first.units.Units.*;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;
import frc.robot.subsystems.CommandSwerveDrivetrain;
//import edu.wpi.first.math.util.Units;


// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public final class Constants {
    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    private static final Slot0Configs steerGains = new Slot0Configs()
        .withKP(85).withKI(0).withKD(0.5)
        .withKS(0.1).withKV(2.66).withKA(0)
        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    private static final Slot0Configs driveGains = new Slot0Configs()
        .withKP(0.1).withKI(0).withKD(0)
        .withKS(0).withKV(0.124);

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;

    // The type of motor used for the drive motor
    private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
    // The type of motor used for the steer motor
    private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;

    // The remote sensor feedback type to use for the steer motors;
    // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.FusedCANcoder;

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current kSlipCurrent = Amps.of(120.0);

    // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration()
    .withCurrentLimits(

        new CurrentLimitsConfigs()
            .withStatorCurrentLimit(Amps.of(120))  // Primary limit for torque/power control
            .withStatorCurrentLimitEnable(true)
            .withSupplyCurrentLimit(Amps.of(70))   // Optional: For extra brownout protection
            .withSupplyCurrentLimitEnable(true)
    );
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                // Swerve azimuth does not require much torque output, so we can set a relatively low
                // stator current limit to help avoid brownouts without impacting performance.
                .withStatorCurrentLimit(Amps.of(60))
                .withStatorCurrentLimitEnable(true)
        );
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Pigeon2Configuration pigeonConfigs = null;

    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    public static final CANBus kCANBus = new CANBus("", "./logs/example.hoot");

    // Theoretical free speed (m/s) at 12 V applied output; This needs to be tuned to your individual robot
    public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(5.21);

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns; This may need to be tuned to your individual robot
    private static final double kCoupleRatio = 3.5714285714285716;

    private static final double kDriveGearRatio = 6.122448979591837;
    private static final double kSteerGearRatio = 21.428571428571427;
    private static final Distance kWheelRadius = Inches.of(2);

    private static final boolean kInvertLeftSide = false;
    private static final boolean kInvertRightSide = true;

    private static final int kPigeonId = 1;

    // These are only used for simulation
    private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
    // Simulated voltage necessary to overcome friction
    private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
    private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);

    public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
            .withCANBusName(kCANBus.getName())
            .withPigeon2Id(kPigeonId)
            .withPigeon2Configs(pigeonConfigs);

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator =
        new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(kDriveGearRatio)
            .withSteerMotorGearRatio(kSteerGearRatio)
            .withCouplingGearRatio(kCoupleRatio)
            .withWheelRadius(kWheelRadius)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
            .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
            .withSlipCurrent(kSlipCurrent)
            .withSpeedAt12Volts(kSpeedAt12Volts)
            .withDriveMotorType(kDriveMotorType)
            .withSteerMotorType(kSteerMotorType)
            .withFeedbackSource(kSteerFeedbackType)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withEncoderInitialConfigs(encoderInitialConfigs)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage);


    // Front Left
    private static final int kFrontLeftDriveMotorId = 43;
    private static final int kFrontLeftSteerMotorId = 41;
    private static final int kFrontLeftEncoderId = 42;
    private static final Angle kFrontLeftEncoderOffset = Rotations.of(-0.277587890625);
    private static final boolean kFrontLeftSteerMotorInverted = true;
    private static final boolean kFrontLeftEncoderInverted = false;

    private static final Distance kFrontLeftXPos = Inches.of(12.375);
    private static final Distance kFrontLeftYPos = Inches.of(12.375);

    // Front Right
    private static final int kFrontRightDriveMotorId = 13;
    private static final int kFrontRightSteerMotorId = 11;
    private static final int kFrontRightEncoderId = 12;
    private static final Angle kFrontRightEncoderOffset = Rotations.of(0.345703125);
    private static final boolean kFrontRightSteerMotorInverted = true;
    private static final boolean kFrontRightEncoderInverted = false;

    private static final Distance kFrontRightXPos = Inches.of(12.375);
    private static final Distance kFrontRightYPos = Inches.of(-12.375);

    // Back Left
    private static final int kBackLeftDriveMotorId = 33;
    private static final int kBackLeftSteerMotorId = 31;
    private static final int kBackLeftEncoderId = 32;
    private static final Angle kBackLeftEncoderOffset = Rotations.of(0.075927734375);
    private static final boolean kBackLeftSteerMotorInverted = true;
    private static final boolean kBackLeftEncoderInverted = false;

    private static final Distance kBackLeftXPos = Inches.of(-12.375);
    private static final Distance kBackLeftYPos = Inches.of(12.375);

    // Back Right
    private static final int kBackRightDriveMotorId = 23;
    private static final int kBackRightSteerMotorId = 21;
    private static final int kBackRightEncoderId = 22;
    private static final Angle kBackRightEncoderOffset = Rotations.of(-0.15380859375);
    private static final boolean kBackRightSteerMotorInverted = true;
    private static final boolean kBackRightEncoderInverted = false;

    private static final Distance kBackRightXPos = Inches.of(-12.375);
    private static final Distance kBackRightYPos = Inches.of(-12.375);


    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft =
        ConstantCreator.createModuleConstants(
            kFrontLeftSteerMotorId, kFrontLeftDriveMotorId, kFrontLeftEncoderId, kFrontLeftEncoderOffset,
            kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted, kFrontLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight =
        ConstantCreator.createModuleConstants(
            kFrontRightSteerMotorId, kFrontRightDriveMotorId, kFrontRightEncoderId, kFrontRightEncoderOffset,
            kFrontRightXPos, kFrontRightYPos, kInvertRightSide, kFrontRightSteerMotorInverted, kFrontRightEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft =
        ConstantCreator.createModuleConstants(
            kBackLeftSteerMotorId, kBackLeftDriveMotorId, kBackLeftEncoderId, kBackLeftEncoderOffset,
            kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted, kBackLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight =
        ConstantCreator.createModuleConstants(
            kBackRightSteerMotorId, kBackRightDriveMotorId, kBackRightEncoderId, kBackRightEncoderOffset,
            kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted, kBackRightEncoderInverted
        );

    /**
     * Creates a CommandSwerveDrivetrain instance.
     * This should only be called once in your robot program,.
     */
    public static CommandSwerveDrivetrain createDrivetrain() {
        return new CommandSwerveDrivetrain(
            DrivetrainConstants, FrontLeft, FrontRight, BackLeft, BackRight
        );
    }


// Elbow constants (mirroring Wrist/Arm setup)
public static final int kElbowMotorId = 51; // CAN ID for Talon FXS controlling Elbow motor (change as needed)
public static final int kElbowEncoderId = 52; // CAN ID for WCP Throughbore Encoder (CANcoder)

public static final double kElbowGearRatio = 135.0; // 135:1 gear ratio

public static final Angle kElbowMinPosition = Degrees.of(0); // Minimum allowed position
public static final Angle kElbowMaxPosition = Degrees.of(230); // Maximum allowed position (limit to 120 degrees)

// PID gains for position control on Elbow motor (tune these values; mirroring Wrist)
public static final Slot0Configs elbowPositionGains = new Slot0Configs()
    .withKP(2.0) // Proportional gain
    .withKI(0.0)   // Integral gain
    .withKD(0.1)   // Derivative gain
    .withKS(0.0)   // Feedforward static
    .withKV(0.0)   // Feedforward velocity
    .withKA(0.0);  // Feedforward acceleration

// Current limits for Elbow motor
public static final CurrentLimitsConfigs elbowCurrentLimits = new CurrentLimitsConfigs()
    .withStatorCurrentLimit(Amps.of(40)) // Limit stator current to prevent overheating
    .withStatorCurrentLimitEnable(true);

// elbow CANcoder configuration (absolute encoder)
public static final CANcoderConfiguration elbowEncoderConfigs;
static {
    elbowEncoderConfigs = new CANcoderConfiguration();
    elbowEncoderConfigs.MagnetSensor = new MagnetSensorConfigs();
    elbowEncoderConfigs.MagnetSensor.SensorDirection = SensorDirectionValue.Clockwise_Positive; // Adjust based on encoder mounting
    // Offset in rotations (0–1), measured from Tuner X or Phoenix Tuner
    elbowEncoderConfigs.MagnetSensor.MagnetOffset = 0.068;  // Set this based on values in TunerX - put elbow in mechanical zero and read Absolute Position
    elbowEncoderConfigs.MagnetSensor.AbsoluteSensorDiscontinuityPoint = 0.5;
}

// Add Wrist constants:
public static final int kWristMotorId = 53; // CAN ID for Talon FX controlling Wrist motor
public static final int kWristEncoderId = 54; // CAN ID for WCP Throughbore Encoder (CANcoder)

public static final double kWristGearRatio = 31.25; // Updated gear ratio to 25:1 and then the double pulley change

public static final Angle kWristMinPosition = Degrees.of(90); // Minimum allowed position
public static final Angle kWristMaxPosition = Degrees.of(135); // Maximum allowed position (limit to 45 degrees)


// PID gains for position control on Wrist motor (tune these values)
public static final Slot0Configs wristPositionGains = new Slot0Configs()
    .withKP(2.5) // Proportional gain
    .withKI(0.0)   // Integral gain
    .withKD(0.1)   // Derivative gain
    .withKS(0.0)   // Feedforward static
    .withKV(0.0)   // Feedforward velocity
    .withKA(0.0);  // Feedforward acceleration

// Current limits for Wrist motor
public static final CurrentLimitsConfigs wristCurrentLimits = new CurrentLimitsConfigs()
    .withStatorCurrentLimit(Amps.of(40)) // Limit stator current to prevent overheating
    .withStatorCurrentLimitEnable(true);

// wrist CANcoder configuration (absolute encoder)
public static final CANcoderConfiguration wristEncoderConfigs;
static {
    wristEncoderConfigs = new CANcoderConfiguration();
    wristEncoderConfigs.MagnetSensor = new MagnetSensorConfigs();
    wristEncoderConfigs.MagnetSensor.SensorDirection = SensorDirectionValue.CounterClockwise_Positive; // Adjust based on encoder mounting
       // Offset in rotations (0–1), measured from Tuner X or Phoenix Tuner
    wristEncoderConfigs.MagnetSensor.MagnetOffset = .0255;  //set this based on values in TunerX - put wrist in mechanical zero and read Absolute Position
    wristEncoderConfigs.MagnetSensor.AbsoluteSensorDiscontinuityPoint = 1;

}

// Add Iris constants (for Neo 550 with SparkMax, no gear reduction)
public static final int kIrisMotorId = 55; // CAN ID for SparkMax controlling Iris motor// PID gains for position control on Iris motor (tune these values; defaults for position control)
public static final double kIrisP = 5.0; // Proportional gain (controls response speed; too high causes oscillation).
public static final double kIrisI = 0.0; // Integral gain (corrects steady-state error; keep low to avoid windup).
public static final double kIrisD = 0.1; // Derivative gain (damps oscillation; tune after P).
public static final double kIrisFF = 0.0; // Feedforward gain (pre-empts control effort; often 0 for position, or tune for gravity/velocity if applicable).


// Current limit for Iris motor (safe for Neo 550; adjust as needed; SparkMax takes int amps).
public static final int kIrisCurrentLimit = 20; // Limit to prevent stall/overheat (no units here, as SparkMax API uses int).



    /**
     * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected device types.
     */
    public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
         * @param modules               Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, modules
            );
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency The frequency to run the odometry loop. If
         *                                unspecified or set to 0 Hz, this is 250 Hz on
         *                                CAN FD, and 100 Hz on CAN 2.0.
         * @param modules                 Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency, modules
            );
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
         *                                  unspecified or set to 0 Hz, this is 250 Hz on
         *                                  CAN FD, and 100 Hz on CAN 2.0.
         * @param odometryStandardDeviation The standard deviation for odometry calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param visionStandardDeviation   The standard deviation for vision calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param modules                   Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency,
                odometryStandardDeviation, visionStandardDeviation, modules
            );
        }
    }
}
